# Site settings
title: Federico Lopez-Osorio
email: flopezos@uvm.edu
url: https://flopezo.github.io
description: "..."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Federico Lopez-Osorio

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/flopezos
#  - title: stack-overflow
#    url: 
#  - title: bitbucket
#    url: 
  - title: github
    url: https://github.com/flopezo

# Build settings
markdown: kramdown
permalink: pretty
