# Site settings
title: Federico Lopez-Osorio
email: flopezo84@gmail.com
url: https://flopezo.github.io
description: "Phylogenetics of social wasps"

# Color settings (hex-codes without the leading hash-tag)
color:
  #primary-dark: '#000000'
  primary-dark: '#FF7D68'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/flopezos
  - title: github
    url: https://github.com/flopezo

# Build settings
markdown: kramdown
permalink: pretty
