# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://flopezo.github.io/" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Federico Lopez-Osorio
  #avatar: avatar.png
  #gravatar: # Email MD5 hash
  description: "PHYLOGENETICS, EVOLUTION, AND SOCIAL WASPS" # used by search engines

  # Header and footer text
  header_text: >
     I am a Ph.D. candidate in the Agnarsson Lab at the University of Vermont. My general research interests are phylogenetics and trait evolution. My dissertation research is focused on elucidating the evolutionary relationships of wasps in the subfamily Vespinae, which includes hornets and yellowjackets, using targeted genes and transcriptome sequencing. Furthermore, I investigate the evolution of behavioral traits within Vespinae using phylogenetic comparative methods. More recently, I have begun working on diversification patterns and biogeography of Caribbean spiders.
     
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: "flopezos@uvm.edu"# Full email address, e.g. "sam@example.com"
  flickr:
  github: "flopezo"
  google_plus:
  linkedin:  # Full URL
  stack_exchange:  # Full URL
  twitter: "flopezos"

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"
  
  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
