# Site settings
title: Federico Lopez-Osorio
email: flopezo84@gmail.com
url: https://flopezo.github.io
description: "Phylogenetics of social wasps"

# Color settings (hex-codes without the leading hash-tag)
color:
  #primary-dark: '#000000'
  #primary-dark: '#FF7D68'
  primary-dark: '#027878'
  primary-fuchsia: '#6F0564'
  primary-blue-bell: '#9F8FC6'
  primary-orange: '#FDB632'
  primary-red: '#C22326'
  links: '#9F8FC6'
  links-secondary: '#FFA366'

# Footer settings
footer: Federico Lopez-Osorio

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/flopezos
  - title: github
    url: https://github.com/flopezo

# Build settings
markdown: kramdown
permalink: pretty
