# Site settings
title:       Federico Lopez-Osorio
email:       flopezo84@gmail.com
author:      Federico Lopez-Osorio
description: "Phylogenetic and Evolution of Social Wasps"
baseurl:     ""
url:         "http://www.federicolopez.org"
date_format: "%b %-d, %Y"

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:
google_tag_manager:

# Optional features
#animated:             false
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    true
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false

# Facebook Page integration
# (for instant articles and other stuff)
fb_page: false
fb_page_id: 

# Social icons
github_username: flopezo
bitbucket_username:
stackoverflow_id:
twitter_username: flopezos
google_plus_id:

# Post sharing icons
show_sharing_icons: false
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false

text:
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]
